### PR TITLE
get_changelog_header: Format day as two digits

### PR DESCRIPTION
**Pull request by encukou**
Today is `* Wed Sep 9 2020`, and that just looks wrong.

### CODE REVIEW

**Comment by encukou** [comment]
This needs tests.

**Comment by encukou** [comment]
@hroncok, And this one, please.
Take your time, there's no rush on this repo :)

**Review by hroncok — APPROVED** [review]
This one is easy. Ship it. See also https://pagure.io/rpmdevtools/pull-request/70

**Comment by encukou** [comment]
Thanks!

**Pull request merged**
